#!/bin/bash

#pgrep -x sxhkd > /dev/null || sxhkd &
pkill sxhkd
sxhkd &

my_laptop_external_monitor=$(xrandr --query | grep 'HDMI-1')
if [[ $my_laptop_external_monitor = *connected* ]]; then
	bspc monitor eDP-1 -d 1 2
	bspc monitor HDMI-1 -d 3 4 5 6 7 8 9 0
else
	bspc monitor -d I II III IV V VI VII VIII IX X
fi

bspc config top_padding        0
bspc config bottom_padding     0
bspc config left_padding       0
bspc config right_padding      0
bspc config border_width       5
bspc config window_gap         0

# Borders and gaps
bspc config borderless_monocle     true
bspc config gapless_monocle        true
bspc config adaptative_raise       true
bspc config apply_shadow_property  true
bspc config auto_cancel            true

# Border colors
bspc config normal_border_color "#484848"
bspc config focused_border_color "#1F8999"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"

# It looks like these options get overridden by Compton...
bspc config normal_frame_opacity 0.75
bspc config focused_frame_opacity 0.75

# Multihead behavior
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Focusing behavior
bspc config focus_follows_pointer true
#bspc config history_aware_focus true
#bspc config focus_by_distance true

# Misc
bspc config split_ratio 0.50
bspc config auto_alternate true
bspc config auto_cancel true
bspc config initial_polarity first_child

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Autostart Programs
pkill picom
picom --config /home/ekrkaxx/.config/picom/picom.conf &

if [ -x $HOME/.config/bspwm/extmonitor ];then
    $HOME/.config/bspwm/extmonitor
fi
feh --bg-scale /home/ekrkaxx/Pictures/AdobeStock_396043913_Editorial_Use_Only-718x523.jpeg

#polybar -c $HOME/.config/polybar/config.ini example &
if [ -x /usr/bin/polybar ]; then
	bash $HOME/.config/polybar/launch.sh
fi
pkill xss-lock
xss-lock --transfer-sleep-lock -- i3lock -i /home/ekrkaxx/Pictures/ericsson-lock.png --nofork &
pkill dunst
dunst &
